spring.application.name=desarrollo
server.port=8082

spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=1
spring.datasource.url=jdbc:postgresql://localhost:5432/
spring.datasource.username=postgres
spring.datasource.password=123456

spring.datasource.driver-class-name=org.postgresql.Driver

Dialecto para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
